### PR TITLE
fix postfix config file, preventing from receiving email

### PR DESCRIPTION
**Pull request by FDT2k**

### CODE REVIEW

**Comment by adaline** [comment]
Hi Fabien,
Thank you very much for a pull request :+1: 
Sorry for delay, i was trying to figure out a way to test things locally before i merge it but alas i have not, really need to get a test suit in this project :)

**Comment by hheimbuerger** [comment]
@FDT2k @adaline Can you please explain why those changes are needed, what they affect?

**Comment by FDT2k** [comment]
Hi, sorry about the late answer

I can't reproduce the original issue right now, but postfix kept showing this message about
" warning: do not list domain YOUR_DOMAIN in BOTH mydestination and virtual_mailbox_domains"

preventing me to receive emails. 

It seemed to be an issue with the boot script which, I think, replaced values in this field.

**Comment by hheimbuerger** [comment]
I'm not really a postfix expert, but this PR looks wrong to me. Doesn't this change prevent delivery into local mailboxes?

I seem to remember having that message as well, and if I remember correctly, explanations and possible solutions (depending on the exact cause) are all over Google.

**Pull request merged**
