### PR TITLE
Json config

### PR DESCRIPTION
**Pull request by adaline**
Replacing file mess with a single JSON config file

### CODE REVIEW

**Comment by prologic** [comment]
Nice :+1:

**Comment by adaline** [comment]
Thanks James :)

**Comment by prologic** [comment]
Now let's just make it YAML and we're golden :) Less brakcets and quotes to type ;)

**Comment by adaline** [comment]
Haha, if only YAML had a` jq` equivalent! For now there is another way ;) http://jsontoyaml.com/

**Comment by prologic** [comment]
ajq equivalent?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Mon, Jan 25, 2016 at 9:32 AM, Valentin Arkhipov <notifications@github.com

**Comment by adaline** [comment]
`jq` is a great command line JSON parser: https://stedolan.github.io/jq/

**Comment by prologic** [comment]
Ahh I'm familiar with jq - yes great tool :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Mon, Jan 25, 2016 at 9:50 AM, Valentin Arkhipov <notifications@github.com

**Pull request merged**
